# golangci-lint configuration for otel-worker
run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic
    - gocyclo
    - bodyclose
    - noctx
    - gosec
    - unparam
    - unconvert
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  misspell:
    locale: US

  revive:
    rules:
      - name: var-naming
      - name: package-comments
      - name: exported
      - name: error-return
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: indent-error-flow

  gosec:
    excludes:
      - G404  # Random number not cryptographically secure

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
