// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: proto/distance/v1/distance.proto

package distancev1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DistanceService_CalculateDistanceFromHome_FullMethodName = "/distance.v1.DistanceService/CalculateDistanceFromHome"
	DistanceService_GetJobStatus_FullMethodName              = "/distance.v1.DistanceService/GetJobStatus"
	DistanceService_ListJobs_FullMethodName                  = "/distance.v1.DistanceService/ListJobs"
)

// DistanceServiceClient is the client API for DistanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DistanceService provides operations for calculating distance-from-home metrics
// using OwnTracks GPS data from a PostgreSQL database.
type DistanceServiceClient interface {
	// CalculateDistanceFromHome initiates an async job to calculate distance metrics
	// for a specific date from the fixed home location (40.736097°N, 74.039373°W).
	// Returns a job ID for status polling and result retrieval.
	CalculateDistanceFromHome(ctx context.Context, in *CalculateDistanceRequest, opts ...grpc.CallOption) (*CalculateDistanceResponse, error)
	// GetJobStatus returns the current status of a distance calculation job.
	// Use this to poll for job completion and retrieve results.
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
	// ListJobs returns a list of distance calculation jobs with optional filtering.
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
}

type distanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDistanceServiceClient(cc grpc.ClientConnInterface) DistanceServiceClient {
	return &distanceServiceClient{cc}
}

func (c *distanceServiceClient) CalculateDistanceFromHome(ctx context.Context, in *CalculateDistanceRequest, opts ...grpc.CallOption) (*CalculateDistanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateDistanceResponse)
	err := c.cc.Invoke(ctx, DistanceService_CalculateDistanceFromHome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distanceServiceClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, DistanceService_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distanceServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, DistanceService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistanceServiceServer is the server API for DistanceService service.
// All implementations must embed UnimplementedDistanceServiceServer
// for forward compatibility.
//
// DistanceService provides operations for calculating distance-from-home metrics
// using OwnTracks GPS data from a PostgreSQL database.
type DistanceServiceServer interface {
	// CalculateDistanceFromHome initiates an async job to calculate distance metrics
	// for a specific date from the fixed home location (40.736097°N, 74.039373°W).
	// Returns a job ID for status polling and result retrieval.
	CalculateDistanceFromHome(context.Context, *CalculateDistanceRequest) (*CalculateDistanceResponse, error)
	// GetJobStatus returns the current status of a distance calculation job.
	// Use this to poll for job completion and retrieve results.
	GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	// ListJobs returns a list of distance calculation jobs with optional filtering.
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	mustEmbedUnimplementedDistanceServiceServer()
}

// UnimplementedDistanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDistanceServiceServer struct{}

func (UnimplementedDistanceServiceServer) CalculateDistanceFromHome(context.Context, *CalculateDistanceRequest) (*CalculateDistanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateDistanceFromHome not implemented")
}
func (UnimplementedDistanceServiceServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedDistanceServiceServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedDistanceServiceServer) mustEmbedUnimplementedDistanceServiceServer() {}
func (UnimplementedDistanceServiceServer) testEmbeddedByValue()                         {}

// UnsafeDistanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistanceServiceServer will
// result in compilation errors.
type UnsafeDistanceServiceServer interface {
	mustEmbedUnimplementedDistanceServiceServer()
}

func RegisterDistanceServiceServer(s grpc.ServiceRegistrar, srv DistanceServiceServer) {
	// If the following call panics, it indicates UnimplementedDistanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DistanceService_ServiceDesc, srv)
}

func _DistanceService_CalculateDistanceFromHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateDistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistanceServiceServer).CalculateDistanceFromHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistanceService_CalculateDistanceFromHome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistanceServiceServer).CalculateDistanceFromHome(ctx, req.(*CalculateDistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistanceService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistanceServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistanceService_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistanceServiceServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistanceService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistanceServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistanceService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistanceServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DistanceService_ServiceDesc is the grpc.ServiceDesc for DistanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distance.v1.DistanceService",
	HandlerType: (*DistanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateDistanceFromHome",
			Handler:    _DistanceService_CalculateDistanceFromHome_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _DistanceService_GetJobStatus_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _DistanceService_ListJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/distance/v1/distance.proto",
}
