// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/distance/v1/distance.proto

package distancev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CalculateDistanceRequest initiates a distance calculation job for a specific date.
type CalculateDistanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// date is the target date for distance calculations in YYYY-MM-DD format
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// device_id optionally filters results to a specific OwnTracks device
	// If empty, processes all devices for the date
	DeviceId      string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateDistanceRequest) Reset() {
	*x = CalculateDistanceRequest{}
	mi := &file_proto_distance_v1_distance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDistanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDistanceRequest) ProtoMessage() {}

func (x *CalculateDistanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distance_v1_distance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDistanceRequest.ProtoReflect.Descriptor instead.
func (*CalculateDistanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_distance_v1_distance_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateDistanceRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CalculateDistanceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// CalculateDistanceResponse contains the job ID for async processing.
type CalculateDistanceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id uniquely identifies the calculation job
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// status indicates the initial job state (typically "queued" or "processing")
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// queued_at is the UTC timestamp when the job was created
	QueuedAt      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateDistanceResponse) Reset() {
	*x = CalculateDistanceResponse{}
	mi := &file_proto_distance_v1_distance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDistanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDistanceResponse) ProtoMessage() {}

func (x *CalculateDistanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distance_v1_distance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDistanceResponse.ProtoReflect.Descriptor instead.
func (*CalculateDistanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_distance_v1_distance_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateDistanceResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CalculateDistanceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CalculateDistanceResponse) GetQueuedAt() *timestamp.Timestamp {
	if x != nil {
		return x.QueuedAt
	}
	return nil
}

// GetJobStatusRequest queries the status of a distance calculation job.
type GetJobStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier returned from CalculateDistanceFromHome
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_proto_distance_v1_distance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distance_v1_distance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_distance_v1_distance_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// GetJobStatusResponse returns the current state of a job.
type GetJobStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier for the job
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// status is one of: "queued", "processing", "completed", "failed"
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// queued_at is the UTC timestamp when the job was created
	QueuedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	// started_at is the UTC timestamp when processing began (null if not started)
	StartedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// completed_at is the UTC timestamp when the job finished (null if not complete)
	CompletedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// error_message contains the error details if status is "failed"
	ErrorMessage string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// result contains the job output if status is "completed"
	Result        *JobResult `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_proto_distance_v1_distance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distance_v1_distance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_distance_v1_distance_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetJobStatusResponse) GetQueuedAt() *timestamp.Timestamp {
	if x != nil {
		return x.QueuedAt
	}
	return nil
}

func (x *GetJobStatusResponse) GetStartedAt() *timestamp.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetJobStatusResponse) GetCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *GetJobStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetJobStatusResponse) GetResult() *JobResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// ListJobsRequest filters jobs by status, date range, or device.
type ListJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status filters jobs by state ("queued", "processing", "completed", "failed")
	// Empty string returns all jobs
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// limit is the maximum number of jobs to return (default: 50, max: 500)
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// offset is the starting position for pagination (default: 0)
	Offset int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// date filters jobs to a specific calculation date (YYYY-MM-DD)
	Date string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	// device_id filters jobs to a specific OwnTracks device
	DeviceId      string `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_proto_distance_v1_distance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distance_v1_distance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_distance_v1_distance_proto_rawDescGZIP(), []int{4}
}

func (x *ListJobsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListJobsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ListJobsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// ListJobsResponse returns a list of jobs matching the filter criteria.
type ListJobsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// jobs is the list of distance calculation jobs
	Jobs []*JobSummary `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	// total_count is the total number of jobs matching the filter
	TotalCount int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// limit is the maximum number of jobs returned in this response
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// offset is the starting position used for this request
	Offset        int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_proto_distance_v1_distance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distance_v1_distance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_distance_v1_distance_proto_rawDescGZIP(), []int{5}
}

func (x *ListJobsResponse) GetJobs() []*JobSummary {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListJobsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// JobSummary provides a summary view of a distance calculation job.
type JobSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id uniquely identifies the calculation job
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// status is one of: "queued", "processing", "completed", "failed"
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// date is the target calculation date (YYYY-MM-DD)
	Date string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	// device_id is the OwnTracks device (empty if all devices)
	DeviceId string `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// queued_at is the UTC timestamp when the job was created
	QueuedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	// completed_at is the UTC timestamp when the job finished (null if not complete)
	CompletedAt   *timestamp.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSummary) Reset() {
	*x = JobSummary{}
	mi := &file_proto_distance_v1_distance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSummary) ProtoMessage() {}

func (x *JobSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distance_v1_distance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSummary.ProtoReflect.Descriptor instead.
func (*JobSummary) Descriptor() ([]byte, []int) {
	return file_proto_distance_v1_distance_proto_rawDescGZIP(), []int{6}
}

func (x *JobSummary) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobSummary) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *JobSummary) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *JobSummary) GetQueuedAt() *timestamp.Timestamp {
	if x != nil {
		return x.QueuedAt
	}
	return nil
}

func (x *JobSummary) GetCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// JobResult contains the output of a completed distance calculation job.
type JobResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// csv_path is the Kubernetes volume path to the generated CSV file
	// Format: distance_YYYYMMDD.csv
	CsvPath string `protobuf:"bytes,1,opt,name=csv_path,json=csvPath,proto3" json:"csv_path,omitempty"`
	// total_distance_km is the sum of all distance segments in kilometers
	TotalDistanceKm float64 `protobuf:"fixed64,2,opt,name=total_distance_km,json=totalDistanceKm,proto3" json:"total_distance_km,omitempty"`
	// total_locations is the number of GPS location records processed
	TotalLocations int32 `protobuf:"varint,3,opt,name=total_locations,json=totalLocations,proto3" json:"total_locations,omitempty"`
	// max_distance_km is the maximum distance from home recorded
	MaxDistanceKm float64 `protobuf:"fixed64,4,opt,name=max_distance_km,json=maxDistanceKm,proto3" json:"max_distance_km,omitempty"`
	// min_distance_km is the minimum distance from home recorded
	MinDistanceKm float64 `protobuf:"fixed64,5,opt,name=min_distance_km,json=minDistanceKm,proto3" json:"min_distance_km,omitempty"`
	// date is the calculation date (YYYY-MM-DD)
	Date string `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	// device_id is the OwnTracks device (empty if all devices)
	DeviceId string `protobuf:"bytes,7,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// processing_time_ms is the job execution duration in milliseconds
	ProcessingTimeMs int64 `protobuf:"varint,8,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_proto_distance_v1_distance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distance_v1_distance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_proto_distance_v1_distance_proto_rawDescGZIP(), []int{7}
}

func (x *JobResult) GetCsvPath() string {
	if x != nil {
		return x.CsvPath
	}
	return ""
}

func (x *JobResult) GetTotalDistanceKm() float64 {
	if x != nil {
		return x.TotalDistanceKm
	}
	return 0
}

func (x *JobResult) GetTotalLocations() int32 {
	if x != nil {
		return x.TotalLocations
	}
	return 0
}

func (x *JobResult) GetMaxDistanceKm() float64 {
	if x != nil {
		return x.MaxDistanceKm
	}
	return 0
}

func (x *JobResult) GetMinDistanceKm() float64 {
	if x != nil {
		return x.MinDistanceKm
	}
	return 0
}

func (x *JobResult) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *JobResult) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *JobResult) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

var File_proto_distance_v1_distance_proto protoreflect.FileDescriptor

const file_proto_distance_v1_distance_proto_rawDesc = "" +
	"\n" +
	" proto/distance/v1/distance.proto\x12\vdistance.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"K\n" +
	"\x18CalculateDistanceRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"\x83\x01\n" +
	"\x19CalculateDistanceResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x127\n" +
	"\tqueued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bqueuedAt\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xcd\x02\n" +
	"\x14GetJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x127\n" +
	"\tqueued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bqueuedAt\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12.\n" +
	"\x06result\x18\a \x01(\v2\x16.distance.v1.JobResultR\x06result\"\x88\x01\n" +
	"\x0fListJobsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\"\x8e\x01\n" +
	"\x10ListJobsResponse\x12+\n" +
	"\x04jobs\x18\x01 \x03(\v2\x17.distance.v1.JobSummaryR\x04jobs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xe4\x01\n" +
	"\n" +
	"JobSummary\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x127\n" +
	"\tqueued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bqueuedAt\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xaa\x02\n" +
	"\tJobResult\x12\x19\n" +
	"\bcsv_path\x18\x01 \x01(\tR\acsvPath\x12*\n" +
	"\x11total_distance_km\x18\x02 \x01(\x01R\x0ftotalDistanceKm\x12'\n" +
	"\x0ftotal_locations\x18\x03 \x01(\x05R\x0etotalLocations\x12&\n" +
	"\x0fmax_distance_km\x18\x04 \x01(\x01R\rmaxDistanceKm\x12&\n" +
	"\x0fmin_distance_km\x18\x05 \x01(\x01R\rminDistanceKm\x12\x12\n" +
	"\x04date\x18\x06 \x01(\tR\x04date\x12\x1b\n" +
	"\tdevice_id\x18\a \x01(\tR\bdeviceId\x12,\n" +
	"\x12processing_time_ms\x18\b \x01(\x03R\x10processingTimeMs2\x9b\x02\n" +
	"\x0fDistanceService\x12j\n" +
	"\x19CalculateDistanceFromHome\x12%.distance.v1.CalculateDistanceRequest\x1a&.distance.v1.CalculateDistanceResponse\x12S\n" +
	"\fGetJobStatus\x12 .distance.v1.GetJobStatusRequest\x1a!.distance.v1.GetJobStatusResponse\x12G\n" +
	"\bListJobs\x12\x1c.distance.v1.ListJobsRequest\x1a\x1d.distance.v1.ListJobsResponseB@Z>github.com/stuartshay/otel-worker/proto/distance/v1;distancev1b\x06proto3"

var (
	file_proto_distance_v1_distance_proto_rawDescOnce sync.Once
	file_proto_distance_v1_distance_proto_rawDescData []byte
)

func file_proto_distance_v1_distance_proto_rawDescGZIP() []byte {
	file_proto_distance_v1_distance_proto_rawDescOnce.Do(func() {
		file_proto_distance_v1_distance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_distance_v1_distance_proto_rawDesc), len(file_proto_distance_v1_distance_proto_rawDesc)))
	})
	return file_proto_distance_v1_distance_proto_rawDescData
}

var file_proto_distance_v1_distance_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_distance_v1_distance_proto_goTypes = []any{
	(*CalculateDistanceRequest)(nil),  // 0: distance.v1.CalculateDistanceRequest
	(*CalculateDistanceResponse)(nil), // 1: distance.v1.CalculateDistanceResponse
	(*GetJobStatusRequest)(nil),       // 2: distance.v1.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),      // 3: distance.v1.GetJobStatusResponse
	(*ListJobsRequest)(nil),           // 4: distance.v1.ListJobsRequest
	(*ListJobsResponse)(nil),          // 5: distance.v1.ListJobsResponse
	(*JobSummary)(nil),                // 6: distance.v1.JobSummary
	(*JobResult)(nil),                 // 7: distance.v1.JobResult
	(*timestamp.Timestamp)(nil),       // 8: google.protobuf.Timestamp
}
var file_proto_distance_v1_distance_proto_depIdxs = []int32{
	8,  // 0: distance.v1.CalculateDistanceResponse.queued_at:type_name -> google.protobuf.Timestamp
	8,  // 1: distance.v1.GetJobStatusResponse.queued_at:type_name -> google.protobuf.Timestamp
	8,  // 2: distance.v1.GetJobStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	8,  // 3: distance.v1.GetJobStatusResponse.completed_at:type_name -> google.protobuf.Timestamp
	7,  // 4: distance.v1.GetJobStatusResponse.result:type_name -> distance.v1.JobResult
	6,  // 5: distance.v1.ListJobsResponse.jobs:type_name -> distance.v1.JobSummary
	8,  // 6: distance.v1.JobSummary.queued_at:type_name -> google.protobuf.Timestamp
	8,  // 7: distance.v1.JobSummary.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 8: distance.v1.DistanceService.CalculateDistanceFromHome:input_type -> distance.v1.CalculateDistanceRequest
	2,  // 9: distance.v1.DistanceService.GetJobStatus:input_type -> distance.v1.GetJobStatusRequest
	4,  // 10: distance.v1.DistanceService.ListJobs:input_type -> distance.v1.ListJobsRequest
	1,  // 11: distance.v1.DistanceService.CalculateDistanceFromHome:output_type -> distance.v1.CalculateDistanceResponse
	3,  // 12: distance.v1.DistanceService.GetJobStatus:output_type -> distance.v1.GetJobStatusResponse
	5,  // 13: distance.v1.DistanceService.ListJobs:output_type -> distance.v1.ListJobsResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_distance_v1_distance_proto_init() }
func file_proto_distance_v1_distance_proto_init() {
	if File_proto_distance_v1_distance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_distance_v1_distance_proto_rawDesc), len(file_proto_distance_v1_distance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_distance_v1_distance_proto_goTypes,
		DependencyIndexes: file_proto_distance_v1_distance_proto_depIdxs,
		MessageInfos:      file_proto_distance_v1_distance_proto_msgTypes,
	}.Build()
	File_proto_distance_v1_distance_proto = out.File
	file_proto_distance_v1_distance_proto_goTypes = nil
	file_proto_distance_v1_distance_proto_depIdxs = nil
}
